### PR TITLE
Guid mvar

### PR DESCRIPTION
**Pull request by yomimono**
the git history here is really messy, but I think this is a working rebase on top of the current mirage-qubes.

### CODE REVIEW

**Comment by cfcs** [comment]
Thanks! Let's merge it and deal with stuff as it happens.

**Comment by cfcs** [comment]
Hmm should this maybe have gone into `guid_mvar` instead of `guid_pixels`?

**Comment by yomimono** [comment]
Yyyyyyyyyyyep.

On March 6, 2019 9:15:46 PM GMT+01:00, cfcs <notifications@github.com> wrote:
>Hmm should this maybe have gone into `guid_mvar` instead of
>`guid_pixels`?

-- 
written on a touchscreen; please forgive typos and brevity

**Comment by cfcs** [comment]
merged it into `guid_mvar` :)

**Pull request merged**
